FROM node:16.13.0 as build

WORKDIR /home/app
COPY . ./
RUN npm ci
RUN npm run build

FROM project-name/nginx:v0.01 as deploy

FROM nginx

COPY --from=deploy /var/www/ /var/www/
COPY --from=build /home/app/build/ /var/www/website/
